server:
  port: 8888

eureka:
  instance:
    hostname: 192.168.14.248 # 设置主机名
  client:
    service-url:
      defaultZone: http://192.168.14.248:8889/eureka/

spring:
  application:
    name: eureka-cluster-server